### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by mwolter805** [kvaster/zwavejs-prom#1]
Hello, apologize for the lack of knowledge but how is this plugin installed in an instance using docker? I've tried to look at the docs but found nothing regarding installing. Would it be possible to add step-by-step instructions to the readme? 

Thank you!

**Comment by cnaslain** [comment]
I saw this plugin in ZwaveJS UI > General > Plugins > @kvaster/zwavejs-prom
I guess this is the way to enable it.
Not tested yet.

**Comment by dennyreiter** [comment]
That did work for me, unlike the other plugin
