### ISSUE TITLE
Content-type error since using Prometheus 3

### ISSUE THREAD

**Issue by soso-bc** [kvaster/zwavejs-prom#5]
Hello,

Upgrading to Prometheus 3, I encountered a content-type issue.
Prometheus expects 'text/plain' while the plugin returns 'text/html'

I fixed it locally but I think I would not be the only one.
That's why I give the correction:

> $ grep -n 'register[;.]' Docker/plugins/zwavejs-prom/index.js
5:const register = promCli.register;
81:     res.set('Content-Type', register.contentType);

**Comment by TheAceMan** [comment]
I ran into this as well. Could you explain your work around?

**Comment by soso-bc** [comment]
@TheAceMan
Modify the zwavejs-prom/index.js file to add the 2 lines (At line 5 and 81) returned by the grep command I specified.

**Comment by TheAceMan** [comment]
Ahh, thanks. Didn't realize the grep was ran after the change to show the modifications. Got it working. But this work around will be cleared on pod restart in the kubernetes cluster. Will have to look into a init container or some persistence if this is not going to be fixed.

**Comment by soso-bc** [comment]
You just need to create your own docker image by overloading the initial one.
ex: 

> FROM zwavejs/zwave-js-ui:latest
> 
> COPY plugins/zwavejs-prom/index.js /usr/src/app/node_modules/@kvaster/zwavejs-prom/index.js

**Comment by TheAceMan** [comment]
A bit hackish but the init container is working. Creating a image would require a container registry and pushing new images as zwave-js-ui base updates. Got it all working and hopefully it's a short term.

**Comment by kvaster** [comment]
Fixed by https://github.com/kvaster/zwavejs-prom/pull/6

**Comment by joneshf** [comment]
Ran into this as well. The migration guide for Prometheus actually calls this failure out: https://prometheus.io/docs/prometheus/latest/migration/#scrape-protocols.

If you cannot update to a version of `@kvaster/zwavejs-prom` that fixes this (like me) there's another option in that guide: set the `fallback_scrape_protocol` explicitly.

E.g. If you're running this in k8s (which, surprisingly someone else in this thread seems to be doing!) and using the Prometheus Operator (or at least their CRDs), you can set `fallbackScrapeProtocol` on your `*Monitor`:
```diff
 apiVersion: monitoring.coreos.com/v1
 kind: ServiceMonitor
 metadata:
   name: z-wave-js
   namespace: z-wave-js
 spec:
   endpoints:
     - path: /metrics
       port: ui
+  fallbackScrapeProtocol: PrometheusText1.0.0
   selector:
     matchLabels:
       app.kubernetes.io/component: z-wave-js
       app.kubernetes.io/name: z-wave-js
```
Or whatever.

You should be able to do similar with the `fallback_scrape_protocol` in plain old Prometheus files if you're doing it that way as well.

---

And for the sake of SEO for the next person that runs into this, the error I was receiving looked something like this:
```
Error scraping target: received unsupported Content-Type "text/html; charset=utf-8" and no fallback_scrape_protocol specified for target
```
